### ISSUE TITLE
Can't use your API

### ISSUE THREAD

**Issue by quillaur** [omics-datascience/modulector#36]
Hello,

  Trying to use your search example: http://modulector.org/mirna-aliases/?mirbase_accession_id=MIMAT0000062

Whether I try opening it in my web-browser or using the module requests of python, I get the following error => "modulector.org’s DNS address could not be found."

Your API is down ? Or is it me doing something inappropriate ?

Thank you for your time.

**Comment by Genarito** [comment]
Hi @quillaur!

Modulector was designed for integration with [multiomix.org](https://multiomix.org/) or for deployment on a private server. So the URL of _modulector.org_ is in the documentation as an example.
However, because you need it, we are looking at making a public URL available. We will let you know as soon as it is accessible. 

Thanks for your interest in Modulector! :rocket:

**Comment by quillaur** [comment]
Thank you @Genarito. That makes sense. I close the issue then. I will be interested to know when your API will be publicly available indeed.

Have a good day.

**Comment by Genarito** [comment]
Hi @quillaur,

We're happy to announce that Modulector is now publicly available through the following URL: https://modulector.multiomix.org
Now you can access your query: https://modulector.multiomix.org/mirna-aliases/?mature_mirna=&mirbase_accession_id=MIMAT0000062

Hope you find Modulector useful for your research
